# Generated by Django 3.0.8 on 2020-07-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200727_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.TextField(default='someName', max_length=100),
        ),
    ]
